services:
  llm:
    build:
      context: .
      dockerfile: llm/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434/
      - TOKENIZERS_PARALLELISM=false
    networks:
      - localnet
    volumes:
      - ./llm:/app/llm
      - ./artifacts:/app/artifacts
      - ./rag_docs:/app/rag_docs

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama
    networks:
      - localnet

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    networks:
      - localnet
    volumes:
      - ./frontend:/app/frontend
    environment:
      - BACKEND_URL=http://llm:8000

networks:
  localnet:
    driver: bridge