max_questions: 1
embedding_model: "artifacts/models/all-MiniLM-L6-v2"
rag_dir_path: "rag_docs"
text_splitter:
  chunk_size: 500
  chunk_overlap: 100
ollama:
  # model: "llama3.2:1b"
  model: "qwen:0.5b"
  max_tokens: 20