max_questions: 5
embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
rag_dir_path: "rag_docs"
text_splitter:
  chunk_size: 500
  chunk_overlap: 100
ollama:
  model: "llama3.2:1b"
  max_tokens: 20